#
# ---Choose Your Languages---
# To disable analysis for a certain language, set the language to `false`.
# For help setting your languages:
# http://docs.codeclimate.com/article/169-configuring-analysis-languages
#
languages:
  Ruby: false
  Javascript: false
  PHP: false
  Python: true

#
# ---Exclude Files or Directories---
# List the files or directories you would like excluded from analysis.
# For help setting your exclude paths:
# https://docs.codeclimate.com/docs/advanced-configuration#section-exclude-patterns
#
exclude_paths:
 - "_includes/"
 - "_layouts/"
 - "_pages/"
 - "_posts/"
 - "_sass/"
 - "_site/"
 - "config/"
 - "db/"
 - "dist/"
 - "features/"
 - "**/node_modules/"
 - "**/spec/"
 - "**/test/"
 - "**/tests/"
 - "Tests/"
 - "**/vendor/"
 - "**/*_test.go"
 - "**/*.d.ts"