dist: xenial

services:
  - docker

sudo: required

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

# before_install:
#   - sudo apt-get install ruby
#   - gem install "rubygems-update:<3.0.0" --no-document
#   - gem install bundler:2.0.1

jobs:
  include:
    - stage: Bot
      env: SERVICE_NAME=aix-bot
      script:
        - git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE '^(bot\/|scripts\/)'  || exit 0
        - docker build -q -t aixchatbot/aix-bot -f ./docker/bot.Dockerfile .
        - docker run aixchatbot/aix-bot flake8 --filename=*.py --exclude=__pycache__ --ignore=F821, F841
        - docker run aixchatbot/aix-bot pytest --cov-config=.coveragerc --cov=.
      deploy:
        provider: script
        script: bash ./deploy.sh
        on:
          branch: master
    - stage: Actions
      env: SERVICE_NAME=aix-actions
      script:
        - git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE '^(actions\/|\.travis.yml)'  || exit 0
        - docker build -q -t aixchatbot/aix-actions -f ./actions/actions.Dockerfile ./actions
        - docker run aixchatbot/aix-actions run flake8 --filename=*.py --exclude=__pycache__ actions
      deploy:
        provider: script
        script: bash ./deploy.sh
        on:
         branch: master
