#
# Basic settings.
#
# URL to test in your machine
# url: http://localhost:4000
# baseurl: ""
# URL in deploy to your Page
url: https://fga-eps-mds.github.io/2019.1-Aix/
baseurl: 2019.1-Aix/
title: Aix
description: Um ChatBot para te ensinar a programar em Python.
avatar: /assets/img/ogp.png
# favicon: /favicon.ico
favicon: /assets/img/ogp.png
language: pt-br

#
# Icons
#
icons:
  rss: true
  email:
  github: fga-eps-mds
  bitbucket:
  twitter: 
  facebook:
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin: # full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: # full URL
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: pretty

#
# Scripts.
#
google_analytics: # e.g. UA-000000-01
disqus:

#
# Localizations.
#
str_next: Próximo
str_prev: Anterior
str_read_more: Ler mais...
str_search: Procurar
str_recent_posts: Posts Recentes
str_show_all_posts: Mostrar todos os posts

#
# Recent posts.
#
recent_posts_num: 10

#
# Pagination.
#
paginate: 10
paginate_path: page/:num

#
# Social.
#
share_buttons:
  twitter: true
  facebook: false
  hatena: false
ogp:
  image_url: https://fga-eps-mds.github.io/2019.1-Aix/assets/img/ogp.png
  fb:
    admin:
    app_id:

#
# Plugins.
#
gems:
  - jekyll-paginate
  - jekyll-feed
  - jemoji

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
