version: '3.7'

services:

  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile-dev
    volumes:
      - './services/api:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig # sets environemnt config

  rasa_core:
    image: rasa/rasa_core
    ports:
      - 5005:5005
    volumes:
      - ./services/core/models/rasa_core:/app/models
      - ./services/core/config:/app/config
    command:
      - start
      - --core
      - models
      - -c
      - rest
      - --endpoints
      - config/endpoints.yml
      - -u
      - core

  rasa_nlu:
    image: rasa/rasa_nlu:latest-spacy
    volumes:
      - ./services/core/models/rasa_nlu:/app/models
    command:
      - start
      - --path
      - models

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME="${MONGO_USERNAME}"
      - MONGO_INITDB_ROOT_PASSWORD="${MONGO_PASSWORD}"

  action_server:
    image: rasa/rasa_core_sdk
    volumes:
      - ./services/actions:/app/actions

  rabbitmq:
    restart: always
    image: rabbitmq:3.7.14-alpine
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER:"${RABBITMQ_USER}"
      - RABBITMQ_DEFAULT_PASS:"${RABBITMQ_PASSWORD}"
