version: '3.7'

services:

  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile-dev
    volumes:
      - './services/api:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig # sets environemnt config

  rasa_core:
    image: rasa/rasa_core
    ports:
      - 5005:5005
    volumes:
      - ./services/core/models/rasa_core:/app/models
      - ./services/core/config:/app/config
    command:
      - start
      - --core
      - models
      - -c
      - rest
      - --endpoints
      - config/endpoints.yml
      - -u
      - core

  rasa_nlu:
    image: rasa/rasa_nlu:latest-spacy
    volumes:
      - ./services/core/models/rasa_nlu:/app/models
    ports:
      - 5000:5000
    command:
      - start
      - --path
      - models

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo

  action_server:
    image: rasa/rasa_core_sdk
    volumes:
      - ./services/actions:/app/actions

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo
