nlu:
  url: http://rasa_nlu:5000

actions_endpoint:
  url: http://action_server:5055/webhook

tracker_store:
  store_type: mongod
  url: mongodb://mongo:27017
  username: mongo
  password: mongo
  auth_source: admin
